/** Sacred Sanctum — tokens from Stitch export (DESIGN.md / code.html) */
module.exports = {
  colors: {
    sanctum: {
      surface: "#fff8f4",
      "on-surface": "#1f1b15",
      "on-surface-variant": "#45464d",
      "inverse-on-surface": "#faefe5",
      "outline-variant": "#c6c6ce",
      "surface-variant": "#ebe1d7",
      "surface-container": "#f7ece2",
      "surface-container-high": "#f1e6dd",
      "surface-container-low": "#fcf2e8",
      "surface-container-lowest": "#ffffff",
      "on-primary": "#ffffff",
      primary: "#0d152f",
      "primary-container": "#222a45",
      secondary: "#a13f22",
      maroon: "#9b3a1e",
      "maroon-deep": "#7a2c15",
      gold: "#dfc488",
      "gold-mid": "#c9973d",
      ivory: "#fbf6ec",
      "ivory-deep": "#f3eada",
      ink: "#2b2620",
      muted: "#4a433a",
      "card-border": "#e7dfce",
    },
  },
  spacing: {
    "sanctum-margin": "4rem",
    "sanctum-margin-mobile": "1.25rem",
    "sanctum-space-xl": "4rem",
    "sanctum-space-lg": "2.25rem",
    "sanctum-gutter": "1.5rem",
  },
  borderRadius: {
    sanctum: "0.25rem",
    "sanctum-sm": "0.125rem",
    "sanctum-xl": "0.5rem",
    "sanctum-arch": "140px",
  },
  fontFamily: {
    sanctum: ['"EB Garamond"', '"Cormorant Garamond"', "Georgia", "serif"],
    "sanctum-sanskrit": ['"Noto Serif"', '"Noto Serif Devanagari"', "serif"],
  },
  fontSize: {
    "sanctum-display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.01em", fontWeight: "400" }],
    "sanctum-headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "500" }],
    "sanctum-headline-md": ["28px", { lineHeight: "36px", fontWeight: "500" }],
    "sanctum-headline-sm": ["22px", { lineHeight: "30px", fontWeight: "600" }],
    "sanctum-body-lg": ["18px", { lineHeight: "30px", fontWeight: "400" }],
    "sanctum-body-md": ["16px", { lineHeight: "26px", fontWeight: "400" }],
    "sanctum-body-sm": ["14px", { lineHeight: "22px", fontWeight: "400" }],
    "sanctum-label-lg": ["13px", { lineHeight: "18px", letterSpacing: "0.12em", fontWeight: "600" }],
    "sanctum-label-md": ["11px", { lineHeight: "16px", letterSpacing: "0.14em", fontWeight: "600" }],
    "sanctum-verse": ["20px", { lineHeight: "34px", letterSpacing: "0.02em", fontWeight: "400" }],
  },
  boxShadow: {
    sanctum: "0 8px 30px rgba(34, 42, 69, 0.05), 0 1px 3px rgba(201, 151, 61, 0.08)",
  },
};
