import { proseParas } from "@/lib/docContent";

export const ashramRituals = [
  {
    id: "nandi-abhisheka",
    path: "/sevas/nandi-abhisheka",
    title: "Nandi Abhisheka",
    eyebrow: "Seva at the Ashram",
    intro: "A traditional abhisheka to Shiva's faithful companion — held at the grand mantapa.",
    paragraphs: proseParas("nandi_seva", { skip: 1, max: 6 }),
    bookPath: "/sevas/nandi-abhisheka/book",
  },
  {
    id: "ghee-butter-abhisheka",
    path: "/sevas/ghee-butter-abhisheka",
    title: "Ghee / Butter Abhisheka",
    eyebrow: "Sacred offering",
    intro: "Ghee and butter abhisheka offered with devotion at the Ashram sannidhis.",
    paragraphs: proseParas("ganesha_seva", { skip: 1, max: 4 }),
    bookPath: "/sevas/ghee-butter-abhisheka/book",
  },
  {
    id: "alankar",
    path: "/sevas/alankar",
    title: "Alankar",
    eyebrow: "Seasonal alankara",
    intro: "Floral and butter alankaras that honour the deities during festival seasons.",
    paragraphs: proseParas("subramanya_seva", { skip: 1, max: 4 }),
    bookPath: "/sevas/alankar/book",
  },
  {
    id: "ganesh-abhisheka",
    path: "/sevas/ganesh-abhisheka",
    title: "Ganesh Abhisheka",
    eyebrow: "Ganesha Sannidhi",
    intro: "Sacred abhisheka at the Ganesha sannidhi — sweetness, wisdom, and new beginnings.",
    paragraphs: proseParas("ganesha_seva", { skip: 1, max: 6 }),
    bookPath: "/sevas/ganesh-abhisheka/book",
  },
  {
    id: "bhavatarini-seva",
    path: "/sevas/bhavatarini-seva",
    title: "Bhavatarini Seva",
    eyebrow: "Divine Mother",
    intro: "Seva offered to Bhagawathi Srimad Sai Rajarajeshwari with prayer and offering.",
    paragraphs: proseParas("mother_declaration", { skip: 1, max: 3 }),
    bookPath: "/sevas/bhavatarini-seva/book",
  },
  {
    id: "subramanya-seva",
    path: "/sevas/subramanya-seva",
    title: "Subramanya Seva",
    eyebrow: "Subramanya Sannidhi",
    intro: "Abhisheka and seva offered to Lord Subramanya, commander of the divine army.",
    paragraphs: proseParas("subramanya_seva", { skip: 1, max: 6 }),
    bookPath: "/sevas/subramanya-seva/book",
  },
];
