export const shopCategories = [
  { id: "all", label: "All items" },
  { id: "books", label: "Books" },
  { id: "audio", label: "Audio" },
  { id: "videos", label: "Videos" },
  { id: "padukas", label: "Padukas" },
  { id: "stamps", label: "Sacred stamps" },
  { id: "sacred", label: "Sacred images" },
];

export const shopProducts = [
  {
    id: "book-amma-life",
    category: "books",
    name: "Glimpses of Amma — Her Story",
    description: "A biography tracing Amma's human journey and spiritual path.",
    price: 350,
    image: "/ssrrt/Umother.jpg",
    inStock: true,
  },
  {
    id: "book-teachings-vol1",
    category: "books",
    name: "Teachings & Discourses · Vol. I",
    description: "Selected talks and guidance from Amma on daily devotion and seva.",
    price: 280,
    image: "/ssrrt/AmmaGanesha.jpg",
    inStock: true,
  },
  {
    id: "book-children",
    category: "books",
    name: "Children's Stories of Devotion",
    description: "Illustrated stories for young readers from Ashram traditions.",
    price: 180,
    image: "/ssrrt/ManiDweepa.jpg",
    inStock: true,
  },
  {
    id: "audio-bhajans",
    category: "audio",
    name: "Bhajans from the Ashram",
    description: "Recorded bhajans and evening prayers from Karekura.",
    price: 150,
    image: "/ssrrt/ShirdiSai.jpg",
    inStock: true,
  },
  {
    id: "audio-mantras",
    category: "audio",
    name: "Mantra Chants · CD",
    description: "Sacred mantra recordings for home practice and meditation.",
    price: 120,
    image: "/ssrrt/sri-yantra.jpg",
    inStock: true,
  },
  {
    id: "video-narayana",
    category: "videos",
    name: "Narayana Seva Documentary",
    description: "Annual annadaana programme — food offered as sacred seva.",
    price: 200,
    image: "/ssrrt/IMG-20250923-WA0025.jpg",
    inStock: true,
  },
  {
    id: "video-festivals",
    category: "videos",
    name: "Ashram Festivals · Highlights",
    description: "Recorded darshans, temple celebrations and community gatherings.",
    price: 250,
    image: "/ssrrt/ManiDweepa.jpg",
    inStock: true,
  },
  {
    id: "padukas-small",
    category: "padukas",
    name: "Consecrated Padukas · Small",
    description: "Blessed padukas for the home altar — compact size.",
    price: 501,
    image: "/ssrrt/devi-logo.jpg",
    inStock: true,
  },
  {
    id: "padukas-large",
    category: "padukas",
    name: "Consecrated Padukas · Large",
    description: "Blessed padukas for the home altar — standard size.",
    price: 1101,
    image: "/ssrrt/sri-yantra.jpg",
    inStock: true,
  },
  {
    id: "stamps-worship",
    category: "stamps",
    name: "Sacred Worship Stamp Set",
    description: "Traditional stamps for daily puja and sadhana.",
    price: 99,
    image: "/ssrrt/sri-yantra.jpg",
    inStock: true,
  },
  {
    id: "stamps-annadaana",
    category: "stamps",
    name: "Annadaana Seva Stamp Sheet",
    description: "Blessed stamps supporting the Trust's food seva programmes.",
    price: 75,
    image: "/ssrrt/AmmaGanesha.jpg",
    inStock: true,
  },
  {
    id: "sacred-devi-print",
    category: "sacred",
    name: "Mother for Abode · Devi Print",
    description: "A blessed image of Sri Rajarajeshwari for the home altar.",
    price: 450,
    image: "/ssrrt/devi-logo.jpg",
    inStock: true,
  },
  {
    id: "sacred-yantra",
    category: "sacred",
    name: "Sri Yantra · Framed Print",
    description: "Framed Sri Yantra for meditation and altar worship.",
    price: 650,
    image: "/ssrrt/sri-yantra.jpg",
    inStock: true,
  },
  {
    id: "sacred-blessing-card",
    category: "sacred",
    name: "Amma & Ganesha Blessing Card",
    description: "A small consecrated card for travel, desk or gifting.",
    price: 120,
    image: "/ssrrt/AmmaGanesha.jpg",
    inStock: true,
  },
];
